name: Playwright Tests
on:
  push:
    branches: [ main, master ]
    paths:
      - 'actividad3-pagina-dom/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'actividad3-pagina-dom/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: ./actividad3-pagina-dom
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    - name: Install Playwright Browsers
      working-directory: ./actividad3-pagina-dom
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./actividad3-pagina-dom
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: actividad3-pagina-dom/playwright-report/
        retention-days: 30
